//=====================================================================
// RESOURCE.H
//    Window List program (Windows Task Manager replacement program)
// Resource ID header file.
//
// Date Created :  05/06/94
// Last Update  :  12/06/95
// Written By   :  Mario E. De Armas
// Compiler Used:  MS Visual C++ 1.52
//
// Copyright IBM Corporation, 1994-1995. All rights reserved.
//
//
// FILE LOG:
// DATE        | ACTION/CHANGE                           | PROGRAMMER
// 05/06/94    | Creation.                               | MDA
//=====================================================================

//---------------------------------------------------------------------
// LANGUAGE STRING TABLE BASE IDs
//---------------------------------------------------------------------
#define IDSTR_BASE_ENUS                10
#define IDSTR_BASE_ENUK                10
#define IDSTR_BASE_PORT                20
#define IDSTR_BASE_SPAN                30
#define IDSTR_BASE_FREN                40
#define IDSTR_BASE_DUTC                50
#define IDSTR_BASE_DANI                60
#define IDSTR_BASE_GRMN                70
#define IDSTR_BASE_SWED                80
#define IDSTR_BASE_FINN                90
#define IDSTR_BASE_ITAL                100

//---------------------------------------------------------------------
// WINDOW LIST POPUP MENU IDs (NLS MAPPING REQUIRED)
//---------------------------------------------------------------------
#define IDM_WINDOWLIST                 2000
#define IDM_WINDOWLIST_ENUS            2010
#define IDM_WINDOWLIST_ENUK            2010
#define IDM_WINDOWLIST_PORT            2020
#define IDM_WINDOWLIST_SPAN            2030
#define IDM_WINDOWLIST_FREN            2040
#define IDM_WINDOWLIST_DUTC            2050
#define IDM_WINDOWLIST_DANI            2060
#define IDM_WINDOWLIST_GRMN            2070
#define IDM_WINDOWLIST_SWED            2080
#define IDM_WINDOWLIST_FINN            2090
#define IDM_WINDOWLIST_ITAL            2100


//---------------------------------------------------------------------
// WINDOW LIST DIALOG IDs.
//---------------------------------------------------------------------
#define IDD_WINDOWLIST                 201

//---------------------------------------------------------------------
// POPUP MENU ITEMS IDs (NO NLS MAPPING REQUIRED).
//---------------------------------------------------------------------
#define IDM_SHOW                       1000
#define IDM_MINIMIZE                   1001
#define IDM_TILE                       1003
#define IDM_CASCADE                    1004
#define IDM_CLOSE                      1005
#define IDM_HELPINDEX                  1006
#define IDM_HELPGENERAL                1007
#define IDM_HELPUSING                  1008
#define IDM_HELPKEYS                   1009

//---------------------------------------------------------------------
// WINDOW LIST DIALOG CONTROL IDs (NO NLS MAPPING REQUIRED).
//---------------------------------------------------------------------
#define IDC_LISTBOX                    2000

// EOF RESOURCE.H

